In [1]:
'''multidimensional array library
speed is 50x more faster compare to python list
numpy uses fixed types
5 -> 8 bit -> numpy-> int32 or you can customize to int16 or int 8

ex 5 in binary : 00000101

Why NumPy ?
Because it is faster.
why it is faster ?

because it uses fixed type:
ex 5 in binary : is 00000101
In numpy u can represent type as int32(4 bytes), Int 16 or int 8

while in python list: it has to store other information as well
like size,object type, refrence count, onject value=> each 8 byte, single
integer in list takes a lot more space.

numpy uses less memory, while iterating we don't have to type check
numpy uses contiguous memory like in C.

list in python can be scatterd(stored refrences of values in memory),
 but numpy makes sure to use continous memory blocks

CPU SIMD(sigle instruction multiple data) vector processing units,
effective cache utilization, keep closer where you need them

Difference:

List: We can do CRUD ops in List and it is same for NumPy
but a lot more things with NumPy

Application of NumPy: MATLAB replacement and SciPy as well
Plotting: MatPlotLib
As Backend for : Pandas, Digital Photography
Most Important for ML/AI

'''
import numpy as np
#initilization

a = np.array([1,2,3])
print(type(a))

b=np.array([[1,3,4],[0.4,0.5,0.8]])

print(b)

#get dims

print(b.ndim)
print(b.shape)

print(a.dtype) #int32 #b.dtype float64



<class 'numpy.ndarray'>
[[1.  3.  4. ]
 [0.4 0.5 0.8]]
2
(2, 3)
int32


In [4]:
#define dtype while initializing
da = np.array([1,2,3,4,5],dtype='int8')

In [6]:
da.itemsize #says 1 byte

1

In [7]:
total_size = da.size * da.itemsize

In [8]:
total_size #5 bytes


5

In [11]:
#for float it's float64 8 bytes

fl = np.array([1,0.6,1.3])
fl.size * fl.itemsize # 24 bytes

24

In [17]:
#change rows/columns

a = n

In [18]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
a[0,0]
a[0][0]

1.0

In [25]:
#get a row
a[0]
a[0,]
a[0,:]

array([1., 0., 0., 0., 0.])

In [29]:
#get a column
a[:,1] # all rows column 1

array([0., 1., 0., 0., 0.])

In [32]:
# more fancy [row,startIndex:endIndex:stepsize]
a[1:1:1]

array([], shape=(0, 5), dtype=float64)

In [34]:
a[0,0:4:2] # in row 0, from 0 to 4 with stepsize of 2

array([1., 0.])

In [52]:
a[0,1:-1:1] # in row 0, from 0 to 4 with stepsize of 2

array([0., 0., 0.])

In [54]:
#update
a[1,4]=34

In [55]:
a

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0., 34.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [56]:
#replce column with all 5

a[:,3]=5

In [57]:
a

array([[ 1.,  0.,  0.,  5.,  0.],
       [ 0.,  1.,  0.,  5., 34.],
       [ 0.,  0.,  1.,  5.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  5.,  1.]])

In [58]:
#replace row with all 6
a[2,:]=6

In [59]:
a

array([[ 1.,  0.,  0.,  5.,  0.],
       [ 0.,  1.,  0.,  5., 34.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  5.,  1.]])

In [60]:
a

array([[ 1.,  0.,  0.,  5.,  0.],
       [ 0.,  1.,  0.,  5., 34.],
       [ 6.,  6.,  6.,  6.,  6.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  5.,  1.]])

In [68]:
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [66]:
a

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

In [71]:
a[:,:,2:3]

array([[[3],
        [6]],

       [[3],
        [6]]])

In [72]:
a=a+a

In [73]:
a

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]]])

In [75]:
z=np.zeros([2,2 ])
z

array([[0., 0.],
       [0., 0.]])

In [78]:
o=np.ones([2,2],dtype="int8")
o

array([[1, 1],
       [1, 1]], dtype=int8)

In [79]:
full= np.full((3,5),88)

In [80]:
full

array([[88, 88, 88, 88, 88],
       [88, 88, 88, 88, 88],
       [88, 88, 88, 88, 88]])

In [83]:
fl=np.full_like(a,5)

In [84]:
fl

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [98]:
ran = np.random.rand(3,5)

In [99]:
ran

array([[0.12200991, 0.30178492, 0.1373714 , 0.44890731, 0.1023165 ],
       [0.94150126, 0.44225324, 0.87089389, 0.33363841, 0.92678153],
       [0.62761716, 0.96850521, 0.49213765, 0.42751086, 0.01892434]])

In [100]:
#random from existing arr shape
np.random.random_sample(a.shape)

array([[[0.51610522, 0.53256589, 0.65400959],
        [0.77195216, 0.01940672, 0.58515385]],

       [[0.91037762, 0.54364031, 0.08240782],
        [0.18313661, 0.53251942, 0.83609295]]])

In [106]:
#random int
np.random.random_integers(0,9,[3,3])

C:\Users\dheeraj.kumar3\AppData\Local\Temp\ipykernel_33748\850068549.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 9 + 1) instead
  np.random.random_integers(0,9,[3,3])


array([[1, 7, 9],
       [5, 2, 4],
       [0, 4, 8]])

In [107]:
#random int
np.random.randint(5,21,a.shape)

array([[[14,  5, 14],
        [ 8, 14,  6]],

       [[15, 10,  5],
        [ 6, 16, 13]]])

In [110]:
#identity matrix, 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [111]:
#or
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [117]:
#repeat, useful to repeat am array
np.repeat(a,5,axis=0) , #axis=0 means row

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]],

       [[ 2,  4,  6],
        [ 8, 10, 12]]])

In [118]:
#or
np.repeat([[1,2,3]],5,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [119]:
#or
#or
np.repeat([[1,2,3]],5,axis=1)

array([[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]])

In [142]:
mat = np.ones([5,5])
mat[1:-1,1:-1]=0

In [143]:
mat[mat.shape[0]//2,mat.shape[1]//2]=9

In [144]:
mat

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [145]:
#be carefull while copying
a= np.array([1,2,3])

In [148]:
b=a.copy()
b[0]=100

In [153]:
import copy as cp

In [156]:
b=cp.deepcopy(a)

In [157]:
b

array([100,   2,   3])

In [158]:
b[0]=400


In [160]:
a

array([100,   2,   3])

In [174]:
add = a+3
mul = a*2
devide=a/4
pow=a**2
co= np.cos(a)
si=np.sin(a)
ex=np.exp(a)


In [173]:
add,mul,devide,pow,co,si,ex

(array([103,   5,   6]),
 array([200,   4,   6]),
 array([25.  ,  0.5 ,  0.75]),
 array([10000,     4,     9]),
 array([ 0.86231887, -0.41614684, -0.9899925 ]),
 array([-0.50636564,  0.90929743,  0.14112001]),
 array([2.68811714e+43, 7.38905610e+00, 2.00855369e+01]))

In [165]:
a+b

array([500,   4,   6])

In [175]:
#### LLinear Algebra #########
#we are not doing element wise ops, like matrix ,multiplication

a=np.full([2,3],2)

In [177]:
b=np.full([3,2],3)

In [179]:
np.matmul(a,b)

array([[18, 18],
       [18, 18]])

In [181]:
c=np.eye(3)

In [182]:
np.linalg.det(c)

1.0

In [185]:
np.linalg.inv(c)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [187]:
np.linalg.eigvals(c)

array([1., 1., 1.])

In [188]:
### Stats with NumPy ###

np.average([1,2,3])

2.0

In [192]:
np.min([[1,2,4],[6,1,45]],axis=1)

array([1, 1])

In [194]:
### reorg
before = np.array([[1,2,4],[6,1,45]])



In [198]:
after = before.reshape([3,2])
after

array([[ 1,  2],
       [ 4,  6],
       [ 1, 45]])

In [207]:
before.reshape(-1)


array([ 1,  2,  4,  6,  1, 45])

In [208]:
### verticle stack

np.stack(a,b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [209]:
a,b

(array([[2, 2, 2],
        [2, 2, 2]]),
 array([[3, 3],
        [3, 3],
        [3, 3]]))

In [211]:
b=np.copy(a)

In [215]:
np.vstack([a,b])

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [217]:
### Horizontal Stack
np.hstack([a,b])

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [218]:
### LOAD data from file using NumPy

np.genfromtxt("file.txt",",")

FileNotFoundError: 1,2,3,4,5 not found.

In [221]:
#### booleam masking
a>5,a[a>5]


(array([[False, False, False],
        [False, False, False]]),
 array([], dtype=int32))

In [223]:
np.all(a<3,axis=1)

array([ True,  True])

In [224]:
~0

-1

In [225]:
~1

-2

In [228]:
import pandas as pd

df = pd.DataFrame({"name":["Dheeraj","Sanjay","Ali"],"age":[27,29,np.nan]})

In [230]:
df.head()

name   age
0  Dheeraj  27.0
1   Sanjay  29.0
2      Ali   NaN

In [238]:
df["age"]=df["age"].fillna(0)

In [236]:
df

name   age
0  Dheeraj  27.0
1   Sanjay  29.0
2      Ali   0.0

In [244]:
df[(df["age"]>5) & (df["age"]<29)]

name   age
0  Dheeraj  27.0